package com.ingram.dataverse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FindDay implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public FindDay() {
    }




}